name: Run app.py via Webhook

on:
  repository_dispatch:

jobs:
  run-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Create input.json from webhook payload
        run: |
          echo '${{ toJson(github.event.client_payload) }}' > input.json

      - name: Run app.py with parameters
        run: python app.py input.json
